require('nodeunit/reporters/default').run([
  '/shared/tests/basic.js',
  '/shared/tests/scene.js',
  '/shared/tests/validation.js',
  '/shared/tests/lag.js',
  '/shared/tests/input.js',
  '/shared/tests/animation.js',
  '/shared/tests/interpolation.js'
]);
